name: Trigger auto deployment for myblazorapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myblazorapp-AutoDeployTrigger-a4313e1e-d6b3-4082-a4d3-8f568a2e9b92.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ffacr33.azurecr.io
          username: ${{ secrets.MYBLAZORAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.MYBLAZORAPP_REGISTRY_PASSWORD }}
      - name: Show environment details
        uses: azure/CLI@v1
        with:
          inlineScript: |
            pwd
            ls
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ffacr33.azurecr.io/myblazorapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYBLAZORAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n myblazorapp -g ff-conapp-rg --server ffacr33.azurecr.io --username  ${{ secrets.MYBLAZORAPP_REGISTRY_USERNAME }} --password ${{ secrets.MYBLAZORAPP_REGISTRY_PASSWORD }}
            az containerapp update -n myblazorapp -g ff-conapp-rg --image ffacr33.azurecr.io/myblazorapp:${{ github.sha }}
